Update to latest Cumulus
substrate-developer-hub/cumulus-workshop pull request #28
Opened 2020-09-08 16:35 UTC by JoshOrndorff

The main purpose of this PR is to update the workshop to the latest version of all software involved. Specifically, it:

* Uses the latest parachain template
* Uses the latest Polkadot (`rococo-branch`)
* Removes the workaround for obtaining genesis state
* Adds a `specs/snippets-to-copy.md` file to make it easier to update the specs in the future

It does **not**:
- Update the Polkadot JS screenshots.

2020-09-08 17:56 UTC, danforbes requested changes
Awesome changes :pray: Please run Prettier for line lengths.

2020-09-08 17:56 UTC, danforbes commented on 1-prep/1-compiling.md
> +docker images.)
```suggestion
Docker images.)
```

2020-09-08 17:56 UTC, danforbes commented on 1-prep/1-compiling.md
> +first parachains and make cross-chain asset transfers, and as a starting point for developing our own parachains.
```suggestion
first parachains and make cross-chain asset transfers. Later, we will use it as a starting point for developing our own parachains.
```

2020-09-08 17:56 UTC, danforbes commented on 1-prep/2-chain-spec.md
> +You will need a chain specification for your relay chain network. You can use one that ships with this workshop, or create your own. An important criteria to keep in mind is that you must always have
```suggestion
You will need a chain specification for your relay chain network. You can use one that ships with this workshop, or create your own. An important requirement to keep in mind is that you must always have one more relay chain validator than
```

2020-09-08 18:04 UTC, riusricardo approved these changes
LGTM, just needs fixes in the lines length as Dan said.

2020-09-08 18:04 UTC, riusricardo commented on specs/snippets-to-copy.md
> +# Copyable snippets for chainspecs
Thanks for this :+1:

2020-09-08 18:45 UTC, danforbes approved these changes
:pray:

2020-09-08 18:51 UTC, JoshOrndorff commented
CI is unable to build the docker image because of https://github.com/paritytech/cumulus/issues/174

2020-09-09 08:24 UTC, merged

2020-09-09 13:51 UTC, JoshOrndorff commented
Oh wow, the docker image built successfully on subsequent runs? That's good but also surprising.

2020-09-10 10:10 UTC, wheresaddie commented
ran for me, no complaints :1st_place_medal: