[WIP] Update latest rococo-v1
substrate-developer-hub/cumulus-workshop pull request #50
Opened 2021-04-20 03:35 UTC by NukeManDan

- Polkadot @ [`943038a`](https://github.com/paritytech/polkadot/commit/943038a888bfaf736142642e2610b248f7af486c)
- Parachain Template @ [`???`]()
    - FIXME!! needs companion PR! 
- Polkadot JS Apps @ [`e2b51e6 `](https://github.com/polkadot-js/apps/commit/e2b51e6033f0a0c25fffc037be18d1326e1e8f39)

## Included
- [x] rococo note in README, links to commits
- [ ]

2021-04-26 06:58 UTC, al3mart commented on shared/chainspecs/snippets-to-copy.md
> -## Four Validators
Will the four validators config be removed from the workshop ?

2021-04-26 07:01 UTC, al3mart requested changes
Remove [real-overseer](https://github.com/substrate-developer-hub/cumulus-workshop/pull/50/files#diff-45922159fb7197802fa2b309361d0e51dd078728ccd11ea1d544ae5da49c5423R49) feature from polkadot build
`cargo build --release`

Add 4 validator config keys to snippets-to-copy

2021-04-29 11:06 UTC, al3mart approved these changes
I have added Four Validators to `shared/chainspecs/snippets-to-copy.md`

2021-05-03 15:16 UTC, riusricardo approved these changes

2021-05-03 16:17 UTC, merged