Update Chinese Translation -- Issue #57
substrate-developer-hub/cumulus-workshop pull request #65
Opened 2021-05-21 03:01 UTC by davidrhodus

2021-05-21 03:03 UTC, davidrhodus commented
@NukeManDan @shawntabrizi

2021-05-21 05:48 UTC, NukeManDan commented
@jimmychu0807 would you mind a quick review here? 😀

2021-05-21 05:51 UTC, NukeManDan commented
We will also need to bring back the tab here, uncommenting the item

2021-05-21 20:17 UTC, NukeManDan approved these changes
I don't read fluently. But I trust this is good to go. I would still like a quick native speaker to do a quick review 🙏🏼

2021-05-22 01:56 UTC, jimmychu0807 commented
@davidrhodus thank you for the PR on Chinese translation. I will review it in about coming two days.

I saw from your github repo that it seems you are picking up on Substrate? How's your learning experience so far? Mind share more with me? Feel free to contact me in [Element] at @jimmychu0807:matrix.parity.io , and do join our [Substrate Technical channel](https://matrix.to/#/!HzySYSaIhtyWrwiwEV:matrix.org?via=matrix.parity.io&via=matrix.org&via=corepaper.org).

2021-05-22 03:42 UTC, jimmychu0807 commented
@davidrhodus Hi David, thank you for your effort. I took a look in your PR. It seems to me as unfinished work. Is this something still work in progress?

![Screenshot 2021-05-22 at 11 36 45](https://user-images.githubusercontent.com/898091/119213534-4f497c00-baf2-11eb-8e76-15a0061dc227.png)

For example, on the above screenshot.

1. The side menu doesn't match
2. The content structure in the Chinese doesn't quite match the corresponding page in english. Which commit of the english content do you base your translaton from?

2021-05-22 03:43 UTC, jimmychu0807 requested changes
See comment above

2021-05-22 04:16 UTC, davidrhodus commented
> @davidrhodus Hi David, thank you for your effort. I took a look in your PR. It seems to me as unfinished work. Is this something still work in progress?
> 
> ![Screenshot 2021-05-22 at 11 36 45](https://user-images.githubusercontent.com/898091/119213534-4f497c00-baf2-11eb-8e76-15a0061dc227.png)
> 
> For example, on the above screenshot.
> 
> 1. The side menu doesn't match
> 2. The content structure in the Chinese doesn't match the corresponding page in english. Which commit of the english content do you base your translaton from?

Thanks for the feedback, this is very helpful. I am new to markdown and missed comparing a couple of the files.

I will update the PR and include the following:

(1)
- Will update the _sidebar.md file 
- Will the README.md ( I mistakenly did not look at this file. )
- Will translate SettingUpTheBootnode.md 

(2)
I used the master branch for the english content. Please let me know if this is correct, or if I should use a specific branch or commit hash.

2021-05-22 09:13 UTC, jimmychu0807 commented
> I used the master branch for the english content. Please let me know if this is correct, or if I should use a specific branch or commit hash.

Yes the english content in master branch is correct. You can always run the site locally with `yarn install && yarn start` and compared the chinese against the english version see if they match.

2021-05-31 21:18 UTC, NukeManDan commented
@davidrhodus I expect #68 to be very close to finished, and it includes a few new sections. Could this be used to generate the remaining translations once it's merged? 🙏🏼

2021-06-02 02:26 UTC, davidrhodus commented
> See comment above

Hi @jimmychu0807 can you review my latest addition to the pull request? I think everything is covered.

2021-06-02 02:27 UTC, davidrhodus commented
> @davidrhodus I expect #68 to be very close to finished, and it includes a few new sections. Could this be used to generate the remaining translations once it's merged? 🙏🏼

Thanks @NukeManDan for the heads up, I will start the translation on this next.

2021-06-02 06:19 UTC, jimmychu0807 commented
@davidrhodus Could you merge in your PR this branch https://github.com/substrate-developer-hub/cumulus-workshop/tree/zh-57? This is the edit I am working on based on your PR. I have finished review section one. Will do the rest in this or next week. But meanwhile, you could also have a review to make sure all sections are translated based on the `master` branch. I found some section missing.

2021-06-19 01:08 UTC, davidrhodus commented
> See comment above

Updated

2021-06-21 16:16 UTC, NukeManDan commented
@jimmychu0807 when you have a moment to review 🙏🏼

2021-06-21 16:17 UTC, NukeManDan approved these changes
I need to have a native speaker take a look 🙇🏼 , but assuming that passes I approve 😁

2021-06-22 06:38 UTC, jimmychu0807 approved these changes
I have some minor comments on the wording. But overall it is much better and more up to date than the text in the existing version. 

@davidrhodus thanks again.

2021-06-22 06:38 UTC, jimmychu0807 commented on zh-cn/3-parachains/4-more-nodes.md
> +正如我们已经展示的那样，平行链 _can_ 仅使用一个整理器。但是那个配置是不是很分散。攻击者只需要关闭一个节点即可阻止平行链。
正如我们已经展示的那样，平行链 _仅_ 使用一个整理器。但是這種配置不是很分散。攻击者只需要关闭一个节点即可阻止平行链。

2021-06-22 06:38 UTC, jimmychu0807 commented on zh-cn/6-register/1-register.md
> +要在洛可可 _before_ 上进行实验，您需要注册，并鼓励您的团队作为支持者
Rococo 這名字就不需要翻成 `洛可可` 了

2021-06-22 06:38 UTC, jimmychu0807 commented on zh-cn/6-register/1-register.md
> +[洛可可矩阵聊天室](https://matrix.to/#/#rococo:matrix.parity.io)，Parity团队之一
前两个子也不用翻，直接用：Rococo matrix 聊天室

2021-06-22 06:38 UTC, jimmychu0807 commented on zh-cn/6-register/1-register.md
> +＃＃＃ 投标
得用 半型的 `#` 号。這是 markdown 格式。

2021-06-29 03:36 UTC, NukeManDan commented
@davidrhodus - would you be willing to rebase on #77 and tweak the langue for the translation? It's very minor here 🙏🏼
Plus Jimmy's comments, then we are good to get this merged 👍🏼

2021-06-29 03:45 UTC, davidrhodus commented
> @davidrhodus - would you be willing to rebase on #77 and tweak the langue for the translation? It's very minor here 🙏🏼
> Plus Jimmy's comments, then we are good to get this merged 👍🏼

Yes, I'll get this completed over the next day. Thanks for the ping and the new updates. 🙂

2021-07-01 16:27 UTC, NukeManDan commented
#77 is in, this PR should be ready to go on top of that 🚀

2021-07-02 01:38 UTC, NukeManDan commented
migrating to #79

2021-07-02 01:38 UTC, closed without merging